name: Docker Build

on:
  push:
    branches:
      - main
      - docker-ci
    pull_request:

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t dem-site .

      - name: Run container
        run: docker run -d -p 8080:80 --name dem-site dem-site

      - name: Test website
        run: curl --fail http://localhost:8080
